version: '3.8'

services:
  db:
    container_name: cafe_hopper_db
    image: postgres:15
    restart: always
    env_file:
      - ./typescript-backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30

  backend:
    container_name: cafe_hopper_backend
    build: 
      context: ./typescript-backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./typescript-backend/.env
    ports:
      - '3001:8080'
    volumes:                              
      - ./typescript-backend/src:/app/src:delegated   
      - /app/node_modules
    restart: always

  frontend:
    container_name: cafe_hopper_frontend
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile
    env_file:
      - ./react-frontend/.env
    ports:
      - '3000:3000'
    volumes:                              
      - ./react-frontend/src:/app/src:delegated         
      - /app/node_modules 
    environment:                          
      - CHOKIDAR_USEPOLLING=true          
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: